platform :ios, '10.0'

target 'TableViewMVVM' do
  use_frameworks!

  pod 'SDWebImage', '~> 4.0'

  pod 'iOSCoreLibrary', :git => 'git@bitbucket.org:Rocoo/ioscorelibrary.git', :branch => 'master', :submodules => true

#  pod 'iOSCoreLibrary', :path => '/Users/rocoo/Desktop/develop/ios-core-library' , :submodules => true
end
