# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseChat' do
  use_frameworks!
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase'
	
end
