# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChatRoomView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'iOSCoreLibrary', :git => 'ssh://git@git.dunqian.tw:30001/itrd/ios-core-library.git', :branch => 'master', :submodules => true

  pod 'iOSCoreLibrary', :path => '/Users/rocoo/Desktop/develop/ios-core-library' , :submodules => true

  pod 'SDWebImage', '~> 4.0'
end
