# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AlamofireDemo' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 3.4'


end
